package io.swagger.client.models

/**
 * EA1H API
 * \"REST API for EA1H Application\"
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 *
 * @param appVersion
 * @param imei
 * @param updatedOn
 */
data class BikeListRequest (

    val appVersion: kotlin.String? = null,
    val imei: kotlin.String? = null,
    val updatedOn: kotlin.Long? = null
) {
}