/**
 * EA1H API
 * \"REST API for EA1H Application\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param bluetoothAddress 
 * @param connectionString 
 * @param id 
 * @param timestamp 
 * @param userId 
 */
data class EcuAdvertising (

    val bluetoothAddress: kotlin.String? = null,
    val connectionString: kotlin.String? = null,
    val id: kotlin.Long? = null,
    val timestamp: Long? = null,
    val userId: kotlin.String? = null
) {
}