/**
 * EA1H API
 * \"REST API for EA1H Application\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.FCMData
import io.swagger.client.models.FCMNotification

/**
 * 
 * @param &#x60;data&#x60; 
 * @param deviceType 
 * @param notification 
 * @param pushType 
 */
data class FCMNotificationRequest (

    val `data`: FCMData? = null,
    val deviceType: kotlin.String? = null,
    val notification: FCMNotification? = null,
    val pushType: kotlin.String? = null
) {
}