/**
 * Hela API
 * \"REST API for EA1H Application\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param btAdd 
 * @param chasNum 
 * @param cmd 
 * @param createdOn 
 * @param imei 
 * @param isSuc 
 * @param os 
 */
data class LogBluetoothCommandDTO (

    val btAdd: kotlin.String? = null,
    val chasNum: kotlin.String? = null,
    val cmd: kotlin.Long? = null,
    val createdOn: kotlin.String? = null,
    val imei: kotlin.String? = null,
    val isSuc: kotlin.Long? = null,
    val os: kotlin.String? = null
) {
}