/**
 * Hela API
 * \"REST API for EA1H Application\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param accountId 
 * @param appVersion 
 * @param email 
 * @param fcmToken 
 * @param idToken 
 * @param imei 
 * @param os 
 * @param otp 
 * @param phone 
 * @param pwd 
 * @param rt 
 * @param src 
 */
data class LoginDTO (

    val accountId: kotlin.String? = null,
    val appVersion: kotlin.String? = null,
    val email: kotlin.String? = null,
    val fcmToken: kotlin.String? = null,
    val idToken: kotlin.String? = null,
    val imei: kotlin.String? = null,
    val os: kotlin.String? = null,
    val otp: kotlin.String? = null,
    val phone: kotlin.String? = null,
    val pwd: kotlin.String? = null,
    val mdNm: kotlin.String? = null,
    val rt: kotlin.Int? = null,
    val src: kotlin.Int? = null,
    val gyro: kotlin.Boolean? = null,
    val accelero: kotlin.Boolean? = null
) {
}