/**
 * Hela API
 * \"REST API for EA1H Application\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.View

/**
 * 
 * @param empty 
 * @param model 
 * @param modelMap 
 * @param reference 
 * @param status 
 * @param view 
 * @param viewName 
 */
data class ModelAndView (

    val empty: kotlin.Boolean? = null,
    val model: kotlin.Any? = null,
    val modelMap: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val reference: kotlin.Boolean? = null,
    val status: ModelAndView.Status? = null,
    val view: View? = null,
    val viewName: kotlin.String? = null
) {
    /**
    * 
    */
    enum class Status(val value: kotlin.String){
    }
}