/**
 * EA1H API
 * \"REST API for EA1H Application\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.FCMNotificationRequest

/**
 * 
 * @param fcmRequest 
 * @param userId 
 */
data class NotificationRequest (

    val fcmRequest: FCMNotificationRequest? = null,
    val userId: kotlin.String? = null
) {
}