/**
 * Hela API
 * \"REST API for EA1H Application\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param agreed 
 * @param chasNum 
 * @param qrCode 
 * @param userId 
 */
data class RegisterBike (

    val agreed: kotlin.Boolean? = null,
    val chasNum: kotlin.String? = null,
    val qrCode: kotlin.String? = null,
    val userId: kotlin.String? = null
) {
}