/**
 * Hela API
 * \"REST API for EA1H Application\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.InputStream
import io.swagger.client.models.URI
import io.swagger.client.models.URL

/**
 * 
 * @param description 
 * @param file 
 * @param filename 
 * @param inputStream 
 * @param &#x60;open&#x60; 
 * @param readable 
 * @param uri 
 * @param url 
 */
data class Resource (

    val description: kotlin.String? = null,
    val file: java.io.File? = null,
    val filename: kotlin.String? = null,
    val inputStream: InputStream? = null,
    val `open`: kotlin.Boolean? = null,
    val readable: kotlin.Boolean? = null,
    val uri: URI? = null,
    val url: URL? = null
) {
}