/**
 * Hela API
 * \"REST API for EA1H Application\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param averageSpeed 
 * @param battery 
 * @param bikeId 
 * @param breakCount 
 * @param chassisNumber 
 * @param dapIotTripId 
 * @param distanceCovered 
 * @param endAddress 
 * @param endLat 
 * @param endLon 
 * @param endTime 
 * @param imei 
 * @param latitudes 
 * @param longitudes 
 * @param startAddress 
 * @param startLat 
 * @param startLon 
 * @param startTime 
 * @param tripId 
 * @param updatedOn 
 * @param userId 
 */
data class TripHistory (
    val averageSpeed: kotlin.Double? = null,
    val battery: kotlin.Double? = null,
    val bikeId: kotlin.Long? = null,
    val breakCount: kotlin.Long? = null,
    val chassisNumber: kotlin.String? = null,
    val distanceCovered: kotlin.Double? = null,
    val endAddress: kotlin.String? = null,
    val endLat: kotlin.Double? = null,
    val endLon: kotlin.Double? = null,
    val endTime: kotlin.Long? = null,
    val imei: kotlin.String? = null,
    val startAddress: kotlin.String? = null,
    val startLat: kotlin.Double? = null,
    val startLon: kotlin.Double? = null,
    val startTime: kotlin.Long? = null,
    val tripId: kotlin.String? = null,
    val updatedOn: kotlin.Long? = null,
    val userId: kotlin.String? = null
) {
}