/**
 * Hela API
 * \"REST API for EA1H Application\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.URLStreamHandler

/**
 * 
 * @param authority 
 * @param content 
 * @param defaultPort 
 * @param deserializedFields 
 * @param file 
 * @param host 
 * @param path 
 * @param port 
 * @param protocol 
 * @param query 
 * @param ref 
 * @param serializedHashCode 
 * @param userInfo 
 */
data class URL (

    val authority: kotlin.String? = null,
    val content: kotlin.Any? = null,
    val defaultPort: kotlin.Int? = null,
    val deserializedFields: URLStreamHandler? = null,
    val file: kotlin.String? = null,
    val host: kotlin.String? = null,
    val path: kotlin.String? = null,
    val port: kotlin.Int? = null,
    val protocol: kotlin.String? = null,
    val query: kotlin.String? = null,
    val ref: kotlin.String? = null,
    val serializedHashCode: kotlin.Int? = null,
    val userInfo: kotlin.String? = null
) {
}