/**
 * Hela API
 * \"REST API for EA1H Application\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ChangePasswordDTO
import io.swagger.client.models.ForgotPassword
import io.swagger.client.models.RegisterBike
import io.swagger.client.models.SignUpDTO

/**
 * 
 * @param imei 
 * @param ochangePasswordDTO 
 * @param oforgotPassword 
 * @param oregisterBike 
 * @param os 
 * @param osignUp 
 * @param otp 
 * @param phone 
 * @param rt 
 */
data class ValidateOtpDTO (

    val imei: kotlin.String? = null,
    val ochangePasswordDTO: ChangePasswordDTO? = null,
    val oforgotPassword: ForgotPassword? = null,
    val oregisterBike: RegisterBike? = null,
    val os: kotlin.String? = null,
    val osignUp: SignUpDTO? = null,
    val otp: kotlin.String? = null,
    val phone: kotlin.String? = null,
    val rt: kotlin.Int? = null
) {
}