/**
 * EA1H API
 * \"REST API for EA1H Application\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.models.FCMNotificationRequestForSingleDevice
import io.swagger.client.models.FCMNotificationRequestForTopic
import io.swagger.client.models.NotificationRequest

import io.swagger.client.infrastructure.*

class NotificationControllerApi(basePath: kotlin.String = "http://iymconnected-api-dev.ap-south-1.elasticbeanstalk.com/") : ApiClient(basePath) {

    /**
     * sendFcmNotificationToSingleDevice
     * 
     * @param body oNotificationRequest 
     * @param authorization  
     * @return kotlin.String
     */
    @Suppress("UNCHECKED_CAST")
    fun sendFcmNotificationToSingleDeviceUsingPOST(body: FCMNotificationRequestForSingleDevice, authorization: kotlin.String): kotlin.String {
        val localVariableBody: kotlin.Any? = body
        
        val localVariableHeaders: kotlin.collections.Map<kotlin.String, kotlin.String> = mapOf("Authorization" to authorization)
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/notification/sendFcmNotificationToSingleDevice", headers = localVariableHeaders
        )
        val response = request<kotlin.String>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.String
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * sendFcmNotificationToTopic
     * 
     * @param body oNotificationRequest 
     * @param authorization  
     * @return kotlin.String
     */
    @Suppress("UNCHECKED_CAST")
    fun sendFcmNotificationToTopicUsingPOST(body: FCMNotificationRequestForTopic, authorization: kotlin.String): kotlin.String {
        val localVariableBody: kotlin.Any? = body
        
        val localVariableHeaders: kotlin.collections.Map<kotlin.String, kotlin.String> = mapOf("Authorization" to authorization)
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/notification/sendFcmNotificationToTopic", headers = localVariableHeaders
        )
        val response = request<kotlin.String>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.String
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * sendFcmNotificationToUser
     * 
     * @param body request 
     * @param authorization  
     * @return kotlin.String
     */
    @Suppress("UNCHECKED_CAST")
    fun sendFcmNotificationToUserUsingPOST(body: NotificationRequest, authorization: kotlin.String): kotlin.String {
        val localVariableBody: kotlin.Any? = body
        
        val localVariableHeaders: kotlin.collections.Map<kotlin.String, kotlin.String> = mapOf("Authorization" to authorization)
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/notification/sendFcmNotificationToUser", headers = localVariableHeaders
        )
        val response = request<kotlin.String>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.String
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
